# Generated by Django 3.1 on 2021-09-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('company_name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('experience_level', models.CharField(blank=True, choices=[('T', 'Trainee'), ('J', 'Junior'), ('M', 'Mid'), ('S', 'Senior'), ('E', 'Expert')], max_length=1)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('remote', models.BooleanField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
